### ISSUE TITLE
Errors when loading pkl data file

### ISSUE THREAD

**Issue by BigBinnie** [yrf1/LLM-MassiveMulticultureNormsKnowledge-NCLB#1]
Hi, I met the following error when I tried to load data from the pkl file:
`No module named 'openai.openai_object'`
Could you please share your openai version when saving the pkl file?

**Comment by luciusssss** [comment]
Same problem here. The dependency of the pkl file is unknown. 
Could you please share a json file of CultureAtlas?
Thanks!

**Comment by yrf1** [comment]
I've uploaded a new json file in the same data directory, and communicated with the issue requester directly a while back. The matter should be resolved now. 
-Cheers
